---------------------------------------------------------------------------


MetaPydonHive - a universal client to communicate with the minibee network.


version v0.42


 --- to find out more about the startup options start with 'metapydonhive.py -h'


 --- The client has been started with these options:


{'verbose': False, 'apimode': True, 'ip': '0.0.0.0', 'xbeeerror': False, 'serial': u'/dev/cu.usbserial-DA01OXVN', 'port': 57600, 'createNewFiles': True, 'logdata': False, 'minibees': 20, 'program': 'junxion', 'logdir': '.', 'autostart': False, 'gui_ip': '127.0.0.1', 'config': 'examples/configuration/example_hiveconfig.xml', 'hport': 57120, 'gui_port': None, 'baudrate': 57600, 'host': '127.0.0.1', 'mboffset': 1, 'name': 'pydonhive', 'loglevel': 'info', 'quiet': False, 'ignore': False, 'logname': 'pydon.log', 'clean': False}


---------------------------------------------------------------------------


WARNING: Could not open the file examples/configuration/example_hiveconfig.xml for reading. Does the file exist?


('ignoring unknown minibees', False)


('check for xbee errors', False)


trying to open serial port


('Opening serial port', u'/dev/cu.usbserial-DA01OXVN', True)


initialising communication through serial port


('create new files for unknown minibees', True)


Created OSC listener at (0.0.0.0,57600) and OSC sender to (127.0.0.1,57120) and opened serial port at /dev/cu.usbserial-DA01OXVN. Now waiting for messages.


--------------------------------


Waiting for Server-thread to finish


Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Volumes/Store/jon/miniconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Volumes/Store/jon/miniconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Volumes/Store/jon/miniconda2/lib/python2.7/site-packages/OSC.py", line 1904, in serve_forever
  File "/Volumes/Store/jon/miniconda2/lib/python2.7/SocketServer.py", line 271, in handle_request
    fd_sets = _eintr_retry(select.select, [self], [], [], timeout)
  File "/Volumes/Store/jon/miniconda2/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
error: (9, 'Bad file descriptor')



Done; goodbye


exiting hive loop


('hive loop not running anymore', False)


gui_ip


key is not None


gui_port


---------------------------------------------------------------------------


MetaPydonHive - a universal client to communicate with the minibee network.


version v0.42


 --- to find out more about the startup options start with 'metapydonhive.py -h'


 --- The client has been started with these options:


{'verbose': False, 'apimode': True, 'ip': '0.0.0.0', 'xbeeerror': False, 'serial': u'/dev/cu.usbserial-DA01OXVN', 'port': 57600, 'createNewFiles': True, 'logdata': False, 'minibees': 20, 'program': 'junxion', 'logdir': '.', 'autostart': False, 'gui_ip': '127.0.0.1', 'config': '/Volumes/Store/Drive/MyMDM/MDM Courses/2018-SoSe-Ontohacking/Sense:Stage Workshop/dance-coding/dance-coding-hive.xml', 'hport': 57120, 'gui_port': None, 'baudrate': 57600, 'host': '127.0.0.1', 'mboffset': 1, 'name': 'pydonhive', 'loglevel': 'info', 'quiet': False, 'ignore': False, 'logname': 'pydon.log', 'clean': False}


---------------------------------------------------------------------------


('ignoring unknown minibees', False)


('check for xbee errors', False)


trying to open serial port


('Opening serial port', u'/dev/cu.usbserial-DA01OXVN', True)


initialising communication through serial port


('create new files for unknown minibees', True)


Created OSC listener at (0.0.0.0,57600) and OSC sender to (127.0.0.1,57120) and opened serial port at /dev/cu.usbserial-DA01OXVN. Now waiting for messages.


--------------------------------


Sending config message for MiniBee 1, revision D, firmware 7


Configuration:
 
{'A5': 'TWIClock', 'A4': 'TWIData'}


('confirmconfig', [1, 0, 50, 6, 0, 0, 0])


minibee 1 is configured


--------------------------------


Waiting for Server-thread to finish


Exception in thread Thread-6:
Traceback (most recent call last):
  File "/Volumes/Store/jon/miniconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Volumes/Store/jon/miniconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Volumes/Store/jon/miniconda2/lib/python2.7/site-packages/OSC.py", line 1904, in serve_forever
  File "/Volumes/Store/jon/miniconda2/lib/python2.7/SocketServer.py", line 271, in handle_request
    fd_sets = _eintr_retry(select.select, [self], [], [], timeout)
  File "/Volumes/Store/jon/miniconda2/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
error: (9, 'Bad file descriptor')



Done; goodbye


exiting hive loop


('hive loop not running anymore', False)


